[E 2021-02-18 22:08:46,798 /home/rabbidaemon/miniconda3/lib/python3.8/site-packages/shioaji/utils.py:42:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'ORA-20003: customer_not_exist\nORA-06512: at "STSTX.SGTP_LOGIN_G", line 427\nORA-06512: at line 1', 'ip_address': '34.80.105.195', 'client_name': ''}}
[E 2021-02-18 22:10:59,813 /home/rabbidaemon/miniconda3/lib/python3.8/site-packages/shioaji/utils.py:42:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'ORA-20003: customer_not_exist\nORA-06512: at "STSTX.SGTP_LOGIN_G", line 427\nORA-06512: at line 1', 'ip_address': '34.80.105.195', 'client_name': ''}}
[E 2021-02-18 22:12:36,657 /home/rabbidaemon/miniconda3/lib/python3.8/site-packages/shioaji/utils.py:42:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2021-02-18 22:13:11,636 /home/rabbidaemon/miniconda3/lib/python3.8/site-packages/shioaji/utils.py:42:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2021-02-18 22:13:51,690 /home/rabbidaemon/miniconda3/lib/python3.8/site-packages/shioaji/utils.py:42:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2021-02-18 22:14:31,728 /home/rabbidaemon/miniconda3/lib/python3.8/site-packages/shioaji/utils.py:42:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2021-02-18 22:15:11,749 /home/rabbidaemon/miniconda3/lib/python3.8/site-packages/shioaji/utils.py:42:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2021-02-18 22:15:51,802 /home/rabbidaemon/miniconda3/lib/python3.8/site-packages/shioaji/utils.py:42:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2021-02-18 22:16:31,849 /home/rabbidaemon/miniconda3/lib/python3.8/site-packages/shioaji/utils.py:42:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
[E 2021-02-18 22:17:11,889 /home/rabbidaemon/miniconda3/lib/python3.8/site-packages/shioaji/utils.py:42:raise_resp_error] {'status': {'status_code': 500}, 'response': {'detail': 'Internal Server Error'}}
